version: "3.8"

services:
  mysql:
    image: mysql:mysqlMain
    container_name: mysql-petclinic-latest
    restart: always
    env_file:
      - .env.mysql
    ports:
      - "3306"
    volumes:
      - new_data:/var/lib/mysql

  petclinic:
    image: spring-petclinic-small
    container_name: spring-petclinic-app
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env.app
    ports:
      - "8090:8080"

volumes:
  new_data: